/**
 * Media-variant geographic data
 *
 * These datasets replace the generic "hotspots / economic / techEvents" layers
 * when the active variant is `media`, so the map reflects actual media-industry
 * content rather than the original geopolitical/financial/tech data.
 */
import type { AIDataCenter, EconomicCenter, GulfInvestment, Hotspot, MapTechEventCluster } from '@/types';
import type { StartupHub } from './tech-geo';

// ---------------------------------------------------------------------------
// 1. Media Hotspots – key media-industry regions & editorial flashpoints
//    Replaces INTEL_HOTSPOTS in the `media` variant.
// ---------------------------------------------------------------------------
export const MEDIA_HOTSPOTS: Hotspot[] = [
  {
    id: 'media_beijing',
    name: '北京',
    subtext: '传媒监管中心',
    lat: 39.9,
    lon: 116.4,
    location: '中国·北京',
    keywords: ['cctv', '新华社', '人民日报', '广电总局', '传媒监管', 'beijing media', 'china media policy'],
    agencies: ['CCTV', 'Xinhua', 'NRTA'],
    description: '中国传媒监管与政策中心，广电总局、中央广播电视总台及主要央媒总部所在地。',
    status: '持续监测',
    escalationScore: 3,
    escalationTrend: 'stable',
    escalationIndicators: ['内容审核政策收紧', '平台合规要求升级', 'AI生成内容监管'],
    history: {
      lastMajorEvent: '生成式AI内容管理暂行办法',
      lastMajorEventDate: '2023-07-13',
      precedentCount: 5,
      precedentDescription: '持续收紧的网络内容管理法规，从短视频到AI生成内容',
    },
    whyItMatters: '中国传媒政策影响全球华语内容生态及平台运营策略',
  },
  {
    id: 'media_shanghai',
    name: '上海',
    subtext: '传媒商业枢纽',
    lat: 31.2,
    lon: 121.5,
    location: '中国·上海',
    keywords: ['上海', '广告', '传媒商业', 'shanghai media', 'advertising', 'bilibili'],
    agencies: ['SMG', 'Bilibili', '小红书'],
    description: '中国传媒商业化核心城市，上海文广、B站、小红书等新媒体平台总部聚集地。',
    status: '持续监测',
    escalationScore: 3,
    escalationTrend: 'escalating',
    escalationIndicators: ['短视频广告收入增长', '品牌投放向新平台迁移', '内容电商崛起'],
    history: {
      lastMajorEvent: 'B站商业化加速',
      lastMajorEventDate: '2024-01-01',
      precedentCount: 3,
    },
    whyItMatters: '中国新消费品牌与内容平台融合的前沿阵地',
  },
  {
    id: 'media_shenzhen',
    name: '深圳',
    subtext: '媒介技术中心',
    lat: 22.5,
    lon: 114.1,
    location: '中国·深圳',
    keywords: ['深圳', '腾讯', '华为', '媒介技术', 'shenzhen', 'tencent', 'huawei'],
    agencies: ['Tencent', 'Huawei'],
    description: '媒介技术创新中心，腾讯、华为等公司推动AI生成内容、社交分发与视频技术演进。',
    status: '持续监测',
    escalationScore: 4,
    escalationTrend: 'escalating',
    escalationIndicators: ['AIGC工具大规模应用', '视频号生态扩张', '微信内容分发变革'],
    whyItMatters: '媒介技术基础设施变革影响全球内容生产与分发格局',
  },
  {
    id: 'media_tokyo',
    name: '东京',
    subtext: '动漫与出版中心',
    lat: 35.7,
    lon: 139.7,
    location: '日本·东京',
    keywords: ['tokyo', 'anime', 'manga', 'publishing', 'nhk', '动漫', '出版'],
    agencies: ['NHK', 'Shueisha', 'Kadokawa'],
    description: '全球动漫与出版产业核心城市，NHK及主要出版集团总部。',
    status: '持续监测',
    escalationScore: 2,
    escalationTrend: 'stable',
    escalationIndicators: ['动漫出海收入创新高', 'AI辅助创作引发版权讨论'],
    whyItMatters: '日本动漫产业是全球最大IP输出源之一，版权模式影响深远',
  },
  {
    id: 'media_seoul',
    name: '首尔',
    subtext: 'K-内容出口中心',
    lat: 37.6,
    lon: 127.0,
    location: '韩国·首尔',
    keywords: ['seoul', 'k-pop', 'k-drama', 'korean content', '韩流', 'K-内容'],
    agencies: ['KBS', 'CJ ENM', 'HYBE'],
    description: 'K-内容全球输出中心，韩流文化产业链涵盖音乐、影视、综艺。',
    status: '持续监测',
    escalationScore: 3,
    escalationTrend: 'escalating',
    escalationIndicators: ['Netflix韩国内容投入翻倍', 'HYBE多平台战略', 'K-pop全球巡演扩张'],
    whyItMatters: '韩流内容模式成为亚洲文化出口标杆',
  },
  {
    id: 'media_mumbai',
    name: '孟买',
    subtext: '宝莱坞与区域媒体',
    lat: 19.1,
    lon: 72.9,
    location: '印度·孟买',
    keywords: ['mumbai', 'bollywood', 'india media', '宝莱坞', '印度媒体'],
    agencies: ['Star India', 'Zee', 'NDTV'],
    description: '宝莱坞影视产业中心，印度最大媒体集团总部聚集地。',
    status: '持续监测',
    escalationScore: 3,
    escalationTrend: 'escalating',
    escalationIndicators: ['JioCinema免费流媒体冲击', '区域语言内容爆发', '数字广告增长'],
    whyItMatters: '印度是全球增长最快的数字媒体市场',
  },
  {
    id: 'media_singapore',
    name: '新加坡',
    subtext: '亚太传媒枢纽',
    lat: 1.3,
    lon: 103.8,
    location: '新加坡',
    keywords: ['singapore', 'media hub', 'apac', '亚太传媒', '通讯社'],
    agencies: ['Mediacorp', 'Channel NewsAsia', 'Reuters Asia'],
    description: '亚太传媒枢纽，国际通讯社亚太总部及区域媒体运营中心。',
    status: '持续监测',
    escalationScore: 2,
    escalationTrend: 'stable',
    escalationIndicators: ['区域媒体总部持续迁入', 'AI新闻工具部署'],
    whyItMatters: '亚太新闻流通与媒体商业运营的核心节点',
  },
  {
    id: 'media_hongkong',
    name: '香港',
    subtext: '华语传媒枢纽',
    lat: 22.3,
    lon: 114.2,
    location: '中国·香港',
    keywords: ['hong kong', 'media freedom', '华语媒体', 'hk media', '南华早报'],
    agencies: ['SCMP', 'RTHK', 'Now TV'],
    description: '华语世界最重要的传媒枢纽之一，传统媒体与新媒体交汇点。',
    status: '持续监测',
    escalationScore: 4,
    escalationTrend: 'de-escalating',
    escalationIndicators: ['媒体格局调整持续', '数字订阅增长', '区域记者站缩减'],
    whyItMatters: '香港传媒生态变化是华语新闻自由度的风向标',
  },
  {
    id: 'media_jakarta',
    name: '雅加达',
    subtext: '东南亚数字媒体',
    lat: -6.2,
    lon: 106.8,
    location: '印度尼西亚·雅加达',
    keywords: ['jakarta', 'indonesia media', 'digital media', '东南亚媒体'],
    agencies: ['Kompas', 'Metro TV', 'GoTo'],
    description: '东南亚最大数字媒体市场，短视频与社交电商融合先行区域。',
    status: '持续监测',
    escalationScore: 3,
    escalationTrend: 'escalating',
    escalationIndicators: ['TikTok Shop增长迅猛', '本地内容创作者经济崛起', '区域广告市场扩张'],
    whyItMatters: '印尼是东南亚最大的数字广告和内容消费市场',
  },
  {
    id: 'media_bangkok',
    name: '曼谷',
    subtext: '泰流文化中心',
    lat: 13.8,
    lon: 100.5,
    location: '泰国·曼谷',
    keywords: ['bangkok', 'thai media', 'BL drama', '泰流', '泰国影视'],
    agencies: ['CH3', 'GMMTV', 'Workpoint'],
    description: '泰流文化与区域媒体中心，BL剧及综艺节目在亚洲广泛传播。',
    status: '持续监测',
    escalationScore: 2,
    escalationTrend: 'escalating',
    escalationIndicators: ['泰剧出海加速', 'LINE TV本地化内容增长', '旅游业内容营销'],
    whyItMatters: '泰流是继韩流之后亚洲最具增长潜力的文化输出模式',
  },
  {
    id: 'media_newyork',
    name: '纽约',
    subtext: '全球传媒总部',
    lat: 40.7,
    lon: -74.0,
    location: '美国·纽约',
    keywords: ['new york', 'media capital', 'nytimes', '新闻', '传媒总部'],
    agencies: ['NYT', 'Reuters', 'Bloomberg', 'NBC'],
    description: '全球传媒产业总部，纽约时报、路透社、彭博社等核心媒体集团驻地。',
    status: '持续监测',
    escalationScore: 3,
    escalationTrend: 'stable',
    escalationIndicators: ['AI新闻生成试验', '数字订阅增长放缓', '裁员潮持续'],
    whyItMatters: '纽约传媒业动态影响全球新闻议程设置与商业模式',
  },
  {
    id: 'media_london',
    name: '伦敦',
    subtext: '欧洲传媒中心',
    lat: 51.5,
    lon: -0.1,
    location: '英国·伦敦',
    keywords: ['london', 'bbc', 'guardian', 'uk media', '英国媒体'],
    agencies: ['BBC', 'The Guardian', 'The Economist', 'Financial Times'],
    description: '欧洲传媒核心，BBC及主要英国媒体集团总部。',
    status: '持续监测',
    escalationScore: 2,
    escalationTrend: 'stable',
    escalationIndicators: ['BBC数字化转型', 'AI监管法案推进', '播客广告增长'],
    whyItMatters: 'BBC模式与英国传媒法规对全球公共广播体系有示范效应',
  },
  {
    id: 'media_dubai',
    name: '迪拜',
    subtext: '中东传媒枢纽',
    lat: 25.2,
    lon: 55.3,
    location: '阿联酋·迪拜',
    keywords: ['dubai', 'media city', 'arab media', '中东传媒'],
    agencies: ['Al Arabiya', 'Dubai Media City', 'MBC Group'],
    description: '中东传媒产业中心，迪拜媒体城聚集区域主要媒体集团。',
    status: '持续监测',
    escalationScore: 2,
    escalationTrend: 'stable',
    escalationIndicators: ['MBC Group流媒体扩张', '区域内容制作增长', 'AI新闻编辑室试点'],
    whyItMatters: '中东地区内容消费增长最快，迪拜是区域媒体运营核心',
  },
];

// ---------------------------------------------------------------------------
// 2. Media Demands – audience / content / advertiser demand centers
//    Replaces ECONOMIC_CENTERS in the `media` variant.
// ---------------------------------------------------------------------------
export const MEDIA_DEMANDS: EconomicCenter[] = [
  // ── China ──
  { id: 'md_douyin', name: '抖音', type: 'financial-hub', lat: 39.9, lon: 116.4, country: 'China', description: '短视频内容消费与广告投放最大平台，日活超7亿' },
  { id: 'md_wechat', name: '微信生态', type: 'financial-hub', lat: 22.5, lon: 114.1, country: 'China', description: '公众号+视频号+小程序构成的完整内容-商业闭环' },
  { id: 'md_bilibili', name: 'B站', type: 'financial-hub', lat: 31.2, lon: 121.5, country: 'China', description: 'Z世代社区视频平台，ACG+知识内容核心阵地' },
  { id: 'md_xiaohongshu', name: '小红书', type: 'financial-hub', lat: 31.2, lon: 121.5, country: 'China', description: '种草+内容电商平台，品牌营销必争之地' },
  { id: 'md_weibo', name: '微博', type: 'exchange', lat: 39.9, lon: 116.4, country: 'China', description: '公共舆论场与娱乐营销核心平台' },
  { id: 'md_kuaishou', name: '快手', type: 'financial-hub', lat: 39.9, lon: 116.4, country: 'China', description: '下沉市场短视频+直播电商龙头' },
  // ── Japan ──
  { id: 'md_line_jp', name: 'LINE', type: 'financial-hub', lat: 35.7, lon: 139.7, country: 'Japan', description: '日本最大社交+内容分发平台' },
  { id: 'md_yahoo_jp', name: 'Yahoo! Japan', type: 'exchange', lat: 35.7, lon: 139.7, country: 'Japan', description: '日本门户+新闻+搜索核心入口' },
  // ── South Korea ──
  { id: 'md_naver', name: 'Naver', type: 'exchange', lat: 37.6, lon: 127.0, country: 'South Korea', description: '韩国最大搜索+内容平台，Webtoon IP源头' },
  { id: 'md_kakao', name: 'Kakao', type: 'financial-hub', lat: 37.6, lon: 127.0, country: 'South Korea', description: '韩国社交+内容+娱乐生态，Kakao Page网文IP' },
  // ── India ──
  { id: 'md_jiocinema', name: 'JioCinema', type: 'financial-hub', lat: 19.1, lon: 72.9, country: 'India', description: '印度免费流媒体，Reliance旗下，用户超4亿' },
  { id: 'md_hotstar', name: 'Disney+ Hotstar', type: 'exchange', lat: 19.1, lon: 72.9, country: 'India', description: '印度最大付费流媒体，板球版权驱动' },
  // ── Southeast Asia ──
  { id: 'md_grab', name: 'Grab Media', type: 'financial-hub', lat: 1.3, lon: 103.8, country: 'Singapore', description: '超级App内嵌内容与广告分发' },
  { id: 'md_tokopedia_play', name: 'Tokopedia Play', type: 'financial-hub', lat: -6.2, lon: 106.8, country: 'Indonesia', description: '印尼电商+短视频融合平台' },
  // ── Global ──
  { id: 'md_youtube', name: 'YouTube', type: 'exchange', lat: 37.4, lon: -122.1, country: 'USA', description: '全球最大视频内容平台，创作者经济核心' },
  { id: 'md_tiktok', name: 'TikTok', type: 'exchange', lat: 22.3, lon: 114.2, country: 'Global', description: '全球短视频霸主，内容出海与广告投放新范式' },
  { id: 'md_netflix', name: 'Netflix', type: 'exchange', lat: 34.1, lon: -118.4, country: 'USA', description: '全球订阅制流媒体龙头，亚洲内容投入翻倍' },
  { id: 'md_meta', name: 'Meta (IG/FB)', type: 'exchange', lat: 37.5, lon: -122.2, country: 'USA', description: 'Instagram Reels+Facebook视频，社交视频广告巨头' },
  { id: 'md_spotify', name: 'Spotify', type: 'central-bank', lat: 59.3, lon: 18.1, country: 'Sweden', description: '全球音频/播客平台，广告与订阅双模式' },
  { id: 'md_x', name: 'X (Twitter)', type: 'exchange', lat: 37.8, lon: -122.4, country: 'USA', description: '实时新闻与舆论场，记者与媒体机构核心阵地' },
];

// ---------------------------------------------------------------------------
// 3. Media Events – major media-industry conferences & festivals
//    Replaces techEvents clusters in the `media` variant.
// ---------------------------------------------------------------------------
export const MEDIA_EVENTS: MapTechEventCluster[] = [
  {
    id: 'me_mipcom',
    lat: 43.55,
    lon: 7.02,
    count: 3,
    items: [
      { id: 'mipcom_1', title: 'MIPCOM Cannes', location: 'Cannes, France', lat: 43.55, lng: 7.02, country: 'France', startDate: '2026-10-13', endDate: '2026-10-16', url: 'https://www.mipcom.com', daysUntil: 186 },
      { id: 'mipcom_2', title: 'MIPTV Spring', location: 'Cannes, France', lat: 43.55, lng: 7.02, country: 'France', startDate: '2026-04-14', endDate: '2026-04-16', url: 'https://www.miptv.com', daysUntil: 4 },
      { id: 'mipcom_3', title: 'MIPDOC', location: 'Cannes, France', lat: 43.55, lng: 7.02, country: 'France', startDate: '2026-04-12', endDate: '2026-04-13', url: null, daysUntil: 2 },
    ],
    location: 'Cannes',
    country: 'France',
    soonestDaysUntil: 2,
    soonCount: 2,
  },
  {
    id: 'me_nab',
    lat: 36.1,
    lon: -115.2,
    count: 1,
    items: [
      { id: 'nab_1', title: 'NAB Show', location: 'Las Vegas, USA', lat: 36.1, lng: -115.2, country: 'USA', startDate: '2026-04-18', endDate: '2026-04-22', url: 'https://www.nabshow.com', daysUntil: 8 },
    ],
    location: 'Las Vegas',
    country: 'USA',
    soonestDaysUntil: 8,
  },
  {
    id: 'me_canneslions',
    lat: 43.55,
    lon: 7.02,
    count: 1,
    items: [
      { id: 'cl_1', title: 'Cannes Lions International Festival of Creativity', location: 'Cannes, France', lat: 43.55, lng: 7.02, country: 'France', startDate: '2026-06-16', endDate: '2026-06-20', url: 'https://www.canneslions.com', daysUntil: 67 },
    ],
    location: 'Cannes',
    country: 'France',
    soonestDaysUntil: 67,
  },
  {
    id: 'me_sxsw',
    lat: 30.3,
    lon: -97.7,
    count: 1,
    items: [
      { id: 'sxsw_1', title: 'SXSW', location: 'Austin, USA', lat: 30.3, lng: -97.7, country: 'USA', startDate: '2027-03-12', endDate: '2027-03-18', url: 'https://www.sxsw.com', daysUntil: 336 },
    ],
    location: 'Austin',
    country: 'USA',
    soonestDaysUntil: 336,
  },
  {
    id: 'me_tiff',
    lat: 43.7,
    lon: -79.4,
    count: 1,
    items: [
      { id: 'tiff_1', title: 'Toronto International Film Festival', location: 'Toronto, Canada', lat: 43.7, lng: -79.4, country: 'Canada', startDate: '2026-09-04', endDate: '2026-09-14', url: 'https://www.tiff.net', daysUntil: 147 },
    ],
    location: 'Toronto',
    country: 'Canada',
    soonestDaysUntil: 147,
  },
  {
    id: 'me_biff',
    lat: 35.2,
    lon: 129.0,
    count: 1,
    items: [
      { id: 'biff_1', title: 'Busan International Film Festival', location: 'Busan, South Korea', lat: 35.2, lng: 129.0, country: 'South Korea', startDate: '2026-10-01', endDate: '2026-10-10', url: 'https://www.biff.kr', daysUntil: 174 },
    ],
    location: 'Busan',
    country: 'South Korea',
    soonestDaysUntil: 174,
  },
  {
    id: 'me_tiff_tokyo',
    lat: 35.7,
    lon: 139.7,
    count: 2,
    items: [
      { id: 'tiff_tokyo_1', title: 'Tokyo International Film Festival', location: 'Tokyo, Japan', lat: 35.7, lng: 139.7, country: 'Japan', startDate: '2026-10-28', endDate: '2026-11-05', url: 'https://www.tiff-jp.net', daysUntil: 201 },
      { id: 'tiff_tokyo_2', title: 'Tokyo Anime Award Festival', location: 'Tokyo, Japan', lat: 35.7, lng: 139.7, country: 'Japan', startDate: '2027-03-01', endDate: '2027-03-05', url: null, daysUntil: 325 },
    ],
    location: 'Tokyo',
    country: 'Japan',
    soonestDaysUntil: 201,
  },
  {
    id: 'me_shanghai_tv',
    lat: 31.2,
    lon: 121.5,
    count: 2,
    items: [
      { id: 'stvf_1', title: '上海电视节 (STVF)', location: 'Shanghai, China', lat: 31.2, lng: 121.5, country: 'China', startDate: '2026-06-09', endDate: '2026-06-13', url: null, daysUntil: 60 },
      { id: 'siff_1', title: '上海国际电影节 (SIFF)', location: 'Shanghai, China', lat: 31.2, lng: 121.5, country: 'China', startDate: '2026-06-14', endDate: '2026-06-23', url: null, daysUntil: 65 },
    ],
    location: 'Shanghai',
    country: 'China',
    soonestDaysUntil: 60,
  },
  {
    id: 'me_hkfilmart',
    lat: 22.3,
    lon: 114.2,
    count: 2,
    items: [
      { id: 'hkfilmart_1', title: 'Hong Kong FILMART', location: 'Hong Kong', lat: 22.3, lng: 114.2, country: 'Hong Kong', startDate: '2027-03-17', endDate: '2027-03-20', url: 'https://www.hkfilmart.com', daysUntil: 341 },
      { id: 'hkiff_1', title: 'Hong Kong International Film Festival', location: 'Hong Kong', lat: 22.3, lng: 114.2, country: 'Hong Kong', startDate: '2027-03-27', endDate: '2027-04-07', url: 'https://www.hkiff.org.hk', daysUntil: 351 },
    ],
    location: 'Hong Kong',
    country: 'Hong Kong',
    soonestDaysUntil: 341,
  },
  {
    id: 'me_bbckonf',
    lat: 51.5,
    lon: -0.1,
    count: 2,
    items: [
      { id: 'bbc_1', title: 'BBC Studios Showcase', location: 'London, UK', lat: 51.5, lng: -0.1, country: 'UK', startDate: '2027-04-01', endDate: '2027-04-02', url: null, daysUntil: 356 },
      { id: 'ria_1', title: 'Reuters Institute Conference', location: 'London, UK', lat: 51.5, lng: -0.1, country: 'UK', startDate: '2026-12-03', endDate: '2026-12-04', url: null, daysUntil: 237 },
    ],
    location: 'London',
    country: 'UK',
    soonestDaysUntil: 237,
  },
  {
    id: 'me_spotify_streamon',
    lat: 34.1,
    lon: -118.4,
    count: 1,
    items: [
      { id: 'spot_1', title: 'Spotify Stream On', location: 'Los Angeles, USA', lat: 34.1, lng: -118.4, country: 'USA', startDate: '2027-03-10', endDate: '2027-03-11', url: null, daysUntil: 334 },
    ],
    location: 'Los Angeles',
    country: 'USA',
    soonestDaysUntil: 334,
  },
  {
    id: 'me_mumbrella',
    lat: -33.9,
    lon: 151.2,
    count: 1,
    items: [
      { id: 'mumb_1', title: 'Mumbrella360', location: 'Sydney, Australia', lat: -33.9, lng: 151.2, country: 'Australia', startDate: '2026-06-03', endDate: '2026-06-04', url: 'https://www.mumbrella.com.au', daysUntil: 54 },
    ],
    location: 'Sydney',
    country: 'Australia',
    soonestDaysUntil: 54,
  },
];

// ---------------------------------------------------------------------------
// 4. Media Dissemination Centers – replaces startup hubs in media variant.
// ---------------------------------------------------------------------------
export const MEDIA_DISSEMINATION_CENTERS: StartupHub[] = [
  { id: 'mdc_beijing', name: '央媒传播中枢', city: 'Beijing', country: 'China', lat: 39.9042, lon: 116.4074, tier: 'mega', unicorns: 18, description: '央视、新华社、人民网及政务传播体系高度集中的全国级新闻传播中心。' },
  { id: 'mdc_shanghai', name: '商业内容分发中心', city: 'Shanghai', country: 'China', lat: 31.2304, lon: 121.4737, tier: 'mega', unicorns: 16, description: '品牌广告、视频平台、内容电商和都市媒体协同最活跃的传播中枢。' },
  { id: 'mdc_hongkong', name: '国际华语新闻中心', city: 'Hong Kong', country: 'China', lat: 22.3193, lon: 114.1694, tier: 'major', unicorns: 9, description: '国际媒体、财经新闻与华语受众传播链路的关键节点。' },
  { id: 'mdc_singapore', name: '亚太新闻分发中心', city: 'Singapore', country: 'Singapore', lat: 1.3521, lon: 103.8198, tier: 'major', unicorns: 7, description: '通讯社区域总部、跨境媒体运营和多语种新闻分发的枢纽。' },
  { id: 'mdc_london', name: '欧洲公共传播中心', city: 'London', country: 'UK', lat: 51.5074, lon: -0.1278, tier: 'major', unicorns: 8, description: 'BBC、路透及国际公共传播机构密集分布的欧洲中心。' },
  { id: 'mdc_newyork', name: '全球新闻议程中心', city: 'New York', country: 'USA', lat: 40.7128, lon: -74.0060, tier: 'mega', unicorns: 15, description: '国际媒体总部、财经信息服务和全球议程设置最集中的新闻中心。' },
  { id: 'mdc_seoul', name: '韩流内容传播中心', city: 'Seoul', country: 'South Korea', lat: 37.5665, lon: 126.9780, tier: 'major', unicorns: 6, description: 'K-content 全球传播、娱乐宣发和平台联运的高活跃区域。' },
];

// ---------------------------------------------------------------------------
// 5. AI Media Data Centers – replaces generic AI data centers in media variant.
// ---------------------------------------------------------------------------
export const MEDIA_AI_DATA_CENTERS: AIDataCenter[] = [
  { id: 'madc_beijing', name: '央视云媒智算中心', owner: 'China Media Group', country: 'China', lat: 39.92, lon: 116.45, status: 'existing', chipType: 'H100 / Ascend', chipCount: 28000, powerMW: 48, sector: 'Media AI', note: '支持新闻剪辑、AIGC 审核、智能分发和多模态新闻生产。' },
  { id: 'madc_shanghai', name: 'SMG-AI内容引擎基地', owner: 'SMG', country: 'China', lat: 31.21, lon: 121.49, status: 'existing', chipType: 'A800 / H800', chipCount: 18000, powerMW: 30, sector: 'Media AI', note: '面向视频生成、广告素材自动化和直播切片分发。' },
  { id: 'madc_shenzhen', name: '腾讯媒体智能算力中心', owner: 'Tencent Media Lab', country: 'China', lat: 22.54, lon: 114.06, status: 'planned', chipType: 'H20 / Ascend', chipCount: 24000, powerMW: 42, sector: 'Media AI', note: '重点支撑视频号、内容审核、智能推荐和媒体 agent 工作流。' },
  { id: 'madc_singapore', name: '亚太多语种新闻算力节点', owner: 'Regional Media Cloud', country: 'Singapore', lat: 1.31, lon: 103.86, status: 'existing', chipType: 'H100', chipCount: 16000, powerMW: 26, sector: 'Media AI', note: '用于国际媒体编译、跨语种摘要和区域内容审核。' },
  { id: 'madc_newyork', name: 'Newsroom AI Compute Hub', owner: 'Global News Group', country: 'USA', lat: 40.75, lon: -73.98, status: 'existing', chipType: 'H100', chipCount: 22000, powerMW: 36, sector: 'Media AI', note: '服务实时新闻摘要、商业洞察、广告优化和智能搜索。' },
];

// ---------------------------------------------------------------------------
// 6. Government News Notices – replaces GCC investment markers in media variant.
// ---------------------------------------------------------------------------
export const MEDIA_GOVERNMENT_NOTICES: GulfInvestment[] = [
  {
    id: 'mgn_beijing_press',
    investingEntity: 'Other',
    investingCountry: 'SA',
    targetCountry: '中国',
    targetCountryIso: 'CN',
    sector: 'telecoms',
    assetType: '新闻发布会',
    assetName: '国务院政策例行吹风会',
    lat: 39.908, lon: 116.397,
    investmentUSD: 50000,
    status: 'operational',
    yearAnnounced: 2026,
    description: '涉及内容治理、平台监管、产业扶持和重大舆情的高频权威通告来源。',
    sourceUrl: 'https://www.scio.gov.cn',
    tags: ['政策发布', '新闻办'],
  },
  {
    id: 'mgn_brussels_ec',
    investingEntity: 'Other',
    investingCountry: 'UAE',
    targetCountry: 'Belgium',
    targetCountryIso: 'BE',
    sector: 'telecoms',
    assetType: '官方公告',
    assetName: '欧盟委员会新闻通告',
    lat: 50.85, lon: 4.35,
    investmentUSD: 42000,
    status: 'operational',
    yearAnnounced: 2026,
    description: '聚焦数字服务法、平台治理、版权合规与 AI 监管等官方通告。',
    sourceUrl: 'https://ec.europa.eu',
    tags: ['DSA', '平台监管'],
  },
  {
    id: 'mgn_dc_whitehouse',
    investingEntity: 'Other',
    investingCountry: 'SA',
    targetCountry: 'USA',
    targetCountryIso: 'US',
    sector: 'telecoms',
    assetType: '新闻简报',
    assetName: '白宫新闻简报',
    lat: 38.8977, lon: -77.0365,
    investmentUSD: 46000,
    status: 'operational',
    yearAnnounced: 2026,
    description: '涉及平台监管、国家安全、文化政策和国际传播议题的重要官方口径。',
    sourceUrl: 'https://www.whitehouse.gov/briefing-room/',
    tags: ['白宫', '官方简报'],
  },
  {
    id: 'mgn_seoul_mcis',
    investingEntity: 'Other',
    investingCountry: 'UAE',
    targetCountry: 'South Korea',
    targetCountryIso: 'KR',
    sector: 'telecoms',
    assetType: '部委公告',
    assetName: '韩国文体观光部媒体通告',
    lat: 37.5665, lon: 126.9780,
    investmentUSD: 28000,
    status: 'operational',
    yearAnnounced: 2026,
    description: '围绕 K-content 出海、平台合作和文化产业扶持的政府信号源。',
    sourceUrl: 'https://www.mcst.go.kr',
    tags: ['韩流', '文化政策'],
  },
  {
    id: 'mgn_singapore_mci',
    investingEntity: 'Other',
    investingCountry: 'SA',
    targetCountry: 'Singapore',
    targetCountryIso: 'SG',
    sector: 'telecoms',
    assetType: '监管通报',
    assetName: '新加坡通信及新闻部通报',
    lat: 1.29, lon: 103.85,
    investmentUSD: 22000,
    status: 'operational',
    yearAnnounced: 2026,
    description: '面向跨境平台治理、信息传播规范和国际媒体合作的政策通告节点。',
    sourceUrl: 'https://www.mci.gov.sg',
    tags: ['监管', '跨境平台'],
  },
];
